site:
  title: Solutions Delivery Platform
  url: http://localhost
  start_page: general::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: general/docs
  - url: .
    start_path: deployment-guides
    branches: HEAD
  - url: .
    branches: HEAD
    start_path: learning-labs
  - url: .
    branches: HEAD
    start_path: how-to
  - url: .
    branches: HEAD
    start_path: contribute
ui: 
  bundle: 
    url: https://github.com/steven-terrana/antora-ui-bundle-sass/releases/download/1.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
