site:
  title: Solutions Delivery Platform
  url: http://localhost
content:
  sources:
  - url: ./
    branches: HEAD
ui: 
  bundle: 
    url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"