site:
  title: Solutions Delivery Platform
  url: https://boozallen.github.io/sdp-docs/
  start_page: overview::index.adoc
  keys: 
    google_analytics: 'UA-144247959-2'
content:
  sources:
  - url: https://github.com/boozallen/sdp-docs.git
    branches: master
    start_path: overview

  - url: https://github.com/boozallen/sdp-docs.git
    branches: master
    start_path: learning-labs

  - url: https://github.com/jenkinsci/templating-engine-plugin.git
    branches: master
    tags: .*
    start_path: docs

  - url: https://github.com/boozallen/sdp-libraries.git
    branches: [ master, release/1.2 ]
    tags: .*
    start_path: docs 
    
  - url: https://github.com/boozallen/sdp-iac.git
    branches: master
    start_path: deployment-guides
ui: 
  bundle: 
    url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: googleb68ed66af787ac15.html
    contents: 'google-site-verification: googleb68ed66af787ac15.html'
  - path: ui.yml
    contents: "static_files: [ .nojekyll, googleb68ed66af787ac15.html ]"
